export const DEFAULT_PAGINATION_PAGE = 1;
export const DEFAULT_PAGINATION_LIMIT = 30;
export const DEFAULT_PAGINATION_LINK_PER_VIEW = 10;
export const DEFAULT_START_TIME = 2;
export const DEFAULT_END_TIME = 9999999999;
export const DEFAULT_SYMBOL_LIST = {
  BTCUSDT: 'BTCUSDT',
  ETHUSDT: 'ETHUSDT',
  XRPUSDT: 'XRPUSDT',
};
export const DEFAULT_DASHBOARD_TICKER = 'BTCUSDT';

export const DEFAULT_EMPTY = '';
