export const DEFAULT_OPEN_ORDER_PAGE = 1;
// export const DEFAULT_OPEN_ORDER_LIMIT = 20;
// export const DEFAULT_OPEN_ORDER_PAGINATION_LINK_PER_VIEW = 10;

// TODO make as common

export const DEFAULT_OPEN_ORDER_LIMIT = 30;
export const DEFAULT_OPEN_ORDER_PAGINATION_LINK_PER_VIEW = 10;

export const DEFAULT_SYMBOL_LIST = {
  BTCUSDT: 'BTCUSDT',
  ETHUSDT: 'ETHUSDT',
  XRPUSDT: 'XRPUSDT',
};

export const DEFAULT_EMPTY = '';
